# Generated by Django 5.1.1 on 2024-12-04 08:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_message_file_path),
        ),
        migrations.AlterField(
            model_name='files',
            name='image_path',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_message_image_path),
        ),
    ]
