# Generated by Django 5.1.1 on 2024-12-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_files_file_path_alter_files_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Is_muted', to='core.profile'),
        ),
    ]
