# Generated by Django 5.0.3 on 2024-04-15 05:26

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=core.models.user_group_avatar_path)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('members', models.ManyToManyField(to='core.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='core.profile')),
            ],
        ),
    ]
