# Generated by Django 5.1.1 on 2024-12-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mute_group_alter_mute_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mute',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
    ]
