# Generated by Django 5.0.3 on 2024-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_uploads',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
