# Generated by Django 5.0.3 on 2024-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message_file_uploads_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_uploads',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
