# Generated by Django 5.0.3 on 2024-05-06 10:18

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_message_file_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_uploads',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=core.models.user_message_file_path)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_message', to='core.message')),
            ],
        ),
    ]
