# Generated by Django 5.0.3 on 2024-05-21 03:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_message_file_uploads_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='image_path',
            field=models.FileField(default='', upload_to=core.models.user_message_image_path),
            preserve_default=False,
        ),
    ]
